spring:
  datasource:
    url: ${FUEL_DB_URL}
    username: ${FUEL_DB_USER}
    password: ${FUEL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: America/Santiago

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    cl.fuelonline: INFO
